const additiveData = [

  // ==================== 防腐剂 ====================

  {
    id: 'e202',
    name: '山梨酸钾',
    aliases: ['E202', '山梨酸', 'Potassium Sorbate'],
    code: 'E202',
    category: '防腐剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-25mg/kg体重',
    commonFoods: '酱油、果酱、饮料、糕点、奶酪',
    summary: '安全性高的防腐剂，正常食用无需担心',
    detail: '山梨酸钾通过抑制霉菌、酵母菌和好氧性细菌的脱氢酶系统发挥防腐作用，其防腐效果是苯甲酸钠的5-10倍。在人体内参与正常代谢，最终分解为二氧化碳和水，属于国际公认最安全的防腐剂之一。',
    warning: '',
    source: 'GB2760-2024 / JECFA第11次评估报告'
  },
  {
    id: 'e211',
    name: '苯甲酸钠',
    aliases: ['E211', '苯甲酸', 'Sodium Benzoate'],
    code: 'E211',
    category: '防腐剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-5mg/kg体重',
    commonFoods: '碳酸饮料、果汁、酱油、醋、罐头',
    summary: '常用防腐剂，但与维生素C共存时可能产生微量苯',
    detail: '苯甲酸钠通过抑制微生物细胞呼吸酶系的活性实现防腐，在酸性环境中效果最佳。争议焦点在于其与抗坏血酸（维生素C）共存时，在特定条件下可能生成微量苯——一种已知致癌物，虽生成量极低但引发安全讨论。',
    warning: '避免长期大量饮用同时含苯甲酸钠和维生素C的饮料',
    source: 'GB2760-2024 / JECFA第61次评估报告 / EFSA评估意见'
  },
  {
    id: 'e266',
    name: '脱氢乙酸钠',
    aliases: ['E266', '脱氢醋酸钠', 'Sodium Dehydroacetate'],
    code: 'E266',
    category: '防腐剂',
    safetyLevel: '安全',
    gbStatus: '限量',
    euStatus: '禁止',
    usStatus: '允许',
    adi: '0-0.6mg/kg体重',
    commonFoods: '面包、糕点、黄油、酱菜',
    summary: '广谱防腐剂，2024版国标已大幅缩小使用范围',
    detail: '脱氢乙酸钠对霉菌、酵母菌和细菌均有较强抑制作用，曾广泛用于烘焙食品。2024版GB2760将其从面包和糕点中移除，仅保留在黄油等少数品类中使用，主要基于更严格的风险评估和暴露量重新计算。',
    warning: '',
    source: 'GB2760-2024 / JECFA评估报告'
  },
  {
    id: 'e282',
    name: '丙酸钙',
    aliases: ['E282', '丙酸盐', 'Calcium Propionate'],
    code: 'E282',
    category: '防腐剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面包、糕点、面制品',
    summary: '天然存在的防腐成分，安全性极高',
    detail: '丙酸钙在人体内可正常代谢为丙酸，是人体内脂肪酸代谢的中间产物，也天然存在于瑞士奶酪中。JECFA未设定具体ADI值，表明其安全性极高，正常食用无健康风险。',
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'e220',
    name: '二氧化硫',
    aliases: ['E220', '亚硫酸酐', 'Sulphur Dioxide'],
    code: 'E220',
    category: '防腐剂',
    safetyLevel: '争议',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '允许',
    adi: '0-0.7mg/kg体重',
    commonFoods: '葡萄酒、干果、蜜饯、脱水蔬菜',
    summary: '传统防腐漂白剂，敏感人群可能过敏',
    detail: '二氧化硫兼具防腐和漂白功能，通过抑制微生物酶活性和还原色素发挥作用。争议在于其可诱发哮喘患者的支气管痉挛，敏感人群即使在低浓度下也可能出现呼吸困难等过敏反应。',
    warning: '哮喘患者及亚硫酸盐过敏者应避免含二氧化硫的食品',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'e250',
    name: '亚硝酸钠',
    aliases: ['E250', '亚硝酸盐', 'Sodium Nitrite'],
    code: 'E250',
    category: '防腐剂',
    safetyLevel: '慎用',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '限量',
    adi: '0-0.07mg/kg体重',
    commonFoods: '火腿、香肠、培根、腊肉',
    summary: '肉制品护色防腐剂，过量摄入有致癌风险',
    detail: '亚硝酸钠在肉制品中与肌红蛋白反应生成亚硝基肌红蛋白使肉呈鲜红色，同时抑制肉毒杆菌生长。其风险在于胃内酸性环境下可与仲胺反应生成N-亚硝胺——一种强致癌物，长期过量摄入与胃癌、结直肠癌风险相关。',
    warning: '儿童和孕妇应尽量减少加工肉制品的摄入，避免与高胺食物同食',
    source: 'GB2760-2024 / JECFA第44次评估报告 / IARC专著'
  },
  {
    id: 'e249',
    name: '亚硝酸钾',
    aliases: ['E249', 'Potassium Nitrite'],
    code: 'E249',
    category: '防腐剂',
    safetyLevel: '慎用',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '限量',
    adi: '0-0.07mg/kg体重',
    commonFoods: '火腿、香肠、培根、腊肉',
    summary: '与亚硝酸钠作用相同，致癌风险需警惕',
    detail: '亚硝酸钾的功能和风险与亚硝酸钠完全一致，在肉制品中起护色和防腐作用，同样可在胃内生成致癌的N-亚硝胺。国标对两者的使用限量严格一致，通常不同时使用。',
    warning: '儿童和孕妇应尽量减少加工肉制品的摄入',
    source: 'GB2760-2024 / JECFA第44次评估报告'
  },
  {
    id: 'e251',
    name: '硝酸钠',
    aliases: ['E251', 'Sodium Nitrate'],
    code: 'E251',
    category: '防腐剂',
    safetyLevel: '慎用',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '限量',
    adi: '0-3.7mg/kg体重',
    commonFoods: '火腿、干酪、腌制肉制品',
    summary: '在体内可转化为亚硝酸盐，间接存在致癌风险',
    detail: '硝酸钠本身毒性较低，但进入人体后可被口腔和肠道细菌还原为亚硝酸钠，进而产生与亚硝酸钠相同的N-亚硝胺致癌风险。因此其安全性评估需考虑体内转化因素，ADI值相对宽松但使用范围受限。',
    warning: '儿童和孕妇应尽量减少含硝酸盐的加工肉制品摄入',
    source: 'GB2760-2024 / JECFA第44次评估报告'
  },
  {
    id: 'e214',
    name: '对羟基苯甲酸乙酯',
    aliases: ['E214', '尼泊金乙酯', 'Ethyl p-Hydroxybenzoate'],
    code: 'E214',
    category: '防腐剂',
    safetyLevel: '争议',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '允许',
    adi: '0-10mg/kg体重',
    commonFoods: '酱油、醋、饮料、果酱',
    summary: '尼泊金酯类防腐剂，存在内分泌干扰争议',
    detail: '对羟基苯甲酸乙酯通过破坏微生物细胞膜和抑制酶活性实现防腐，防腐效果受pH影响较小。争议主要来自其与对羟基苯甲酸酯类（Parabens）的关联——部分研究显示Parabens具有弱雌激素活性，但食品中的暴露量远低于产生内分泌影响的阈值。',
    warning: '婴幼儿食品中不建议使用',
    source: 'GB2760-2024 / JECFA第7次评估报告 / EFSA重新评估意见'
  },
  {
    id: 'e234',
    name: '乳酸链球菌素',
    aliases: ['E234', '尼生素', 'Nisin'],
    code: 'E234',
    category: '防腐剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '乳制品、罐头、肉制品',
    summary: '天然生物防腐剂，安全性极高',
    detail: '乳酸链球菌素是由乳酸乳球菌产生的多肽类抗菌物质，专一性抑制革兰氏阳性菌，特别是肉毒杆菌和芽孢杆菌。在人体消化道内被蛋白酶迅速分解为氨基酸，不影响肠道正常菌群，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第32次评估报告'
  },

  // ==================== 甜味剂 ====================

  {
    id: 'e951',
    name: '阿斯巴甜',
    aliases: ['E951', '甜味素', 'Aspartame'],
    code: 'E951',
    category: '甜味剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-40mg/kg体重',
    commonFoods: '无糖饮料、口香糖、酸奶、桌面甜味剂',
    summary: 'IARC列为2B类可能致癌物，JECFA维持现有ADI',
    detail: '阿斯巴甜甜度约为蔗糖的200倍，在体内分解为苯丙氨酸、天冬氨酸和甲醇。2023年IARC基于有限证据将其列为2B类致癌物（可能致癌），但JECFA同期评估认为现有证据不足以改变ADI，争议核心在于动物实验中高剂量与人类实际暴露量之间的差距。',
    warning: '苯丙酮尿症患者禁用；孕妇和儿童建议控制摄入量',
    source: 'GB2760-2024 / JECFA第96次评估报告 / IARC 2023评估'
  },
  {
    id: 'e955',
    name: '三氯蔗糖',
    aliases: ['E955', '蔗糖素', 'Sucralose'],
    code: 'E955',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-15mg/kg体重',
    commonFoods: '无糖饮料、烘焙食品、乳制品、桌面甜味剂',
    summary: '安全性良好的高倍甜味剂，热稳定性优于阿斯巴甜',
    detail: '三氯蔗糖以蔗糖为原料经氯化制得，甜度约为蔗糖的600倍。其分子中氯原子的引入使人体消化酶无法识别和分解，绝大部分以原形排出体外，不参与代谢也不产生热量，热稳定性好，适合烘焙和烹饪。',
    warning: '',
    source: 'GB2760-2024 / JECFA第51次评估报告'
  },
  {
    id: 'e950',
    name: '安赛蜜',
    aliases: ['E950', '乙酰磺胺酸钾', 'Acesulfame K'],
    code: 'E950',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-15mg/kg体重',
    commonFoods: '无糖饮料、口香糖、果冻、桌面甜味剂',
    summary: '常用高倍甜味剂，常与其他甜味剂复配使用',
    detail: '安赛蜜甜度约为蔗糖的200倍，不被人体代谢吸收，直接排出体外。其与阿斯巴甜或三氯蔗糖复配时可产生协同增甜效应，改善单一甜味剂的口感缺陷，是目前最常用的复配甜味方案之一。',
    warning: '',
    source: 'GB2760-2024 / JECFA第37次评估报告'
  },
  {
    id: 'e954',
    name: '糖精钠',
    aliases: ['E954', '糖精', 'Saccharin'],
    code: 'E954',
    category: '甜味剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '限量',
    usStatus: '允许',
    adi: '0-5mg/kg体重',
    commonFoods: '蜜饯、饮料、酱菜、桌面甜味剂',
    summary: '最古老的人工甜味剂，曾因动物实验致癌争议被警告',
    detail: '糖精钠甜度约为蔗糖的300-500倍，不被人体代谢直接排出。早期大鼠实验显示高剂量可致膀胱癌，但后续研究证实该机制为大鼠特有（与尿液成分相关），不适用于人类。尽管如此，其安全性争议至今未完全消除，欧盟限制其在婴幼儿食品中使用。',
    warning: '婴幼儿食品中不允许使用',
    source: 'GB2760-2024 / JECFA第41次评估报告'
  },
  {
    id: 'e952',
    name: '甜蜜素',
    aliases: ['E952', '环己基氨基磺酸钠', 'Cyclamate'],
    code: 'E952',
    category: '甜味剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '禁止',
    commonFoods: '蜜饯、凉果、饮料、果冻',
    summary: '美国禁用但中欧允许的甜味剂，致癌争议持续',
    detail: '甜蜜素甜度约为蔗糖的30-50倍，1969年因大鼠实验显示可能致癌被美国FDA禁用至今。后续大量研究未能证实其对人类的致癌性，JECFA和EFSA均认为安全，但美国始终未解除禁令，成为国际食品贸易的争议焦点。',
    warning: '美国禁用，出口食品需注意',
    source: 'GB2760-2024 / JECFA第82次评估报告'
  },
  {
    id: 'e967',
    name: '木糖醇',
    aliases: ['E967', 'Xylitol'],
    code: 'E967',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '无糖口香糖、糖果、牙膏',
    summary: '天然糖醇，护齿效果显著',
    detail: '木糖醇甜度与蔗糖相当，但不能被口腔致龋菌发酵利用，反而可抑制变形链球菌生长，因此被广泛用于护齿产品。其在体内代谢不需胰岛素参与，适合糖尿病患者，但过量摄入可能引起渗透性腹泻。',
    warning: '',
    source: 'GB2760-2024 / JECFA第27次评估报告'
  },
  {
    id: 'e968',
    name: '赤藓糖醇',
    aliases: ['E968', '赤鲜糖醇', 'Erythritol'],
    code: 'E968',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '无糖饮料、糖果、巧克力、烘焙食品',
    summary: '热量极低的糖醇，口感接近蔗糖',
    detail: '赤藓糖醇甜度约为蔗糖的70%，是热量最低的糖醇（约0.2kcal/g），约90%经小肠吸收后以原形从尿液排出，不参与代谢。其致腹泻阈值高于其他糖醇，且不引起血糖波动，是近年来最受欢迎的代糖之一。',
    warning: '',
    source: 'GB2760-2024 / JECFA第63次评估报告'
  },
  {
    id: 'e965',
    name: '麦芽糖醇',
    aliases: ['E965', 'Maltitol'],
    code: 'E965',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '无糖糖果、巧克力、冰淇淋、烘焙食品',
    summary: '口感最接近蔗糖的糖醇之一',
    detail: '麦芽糖醇甜度约为蔗糖的90%，口感和甜味特性最接近蔗糖，是替代蔗糖制作无糖食品的理想选择。其在体内缓慢水解为葡萄糖和山梨糖醇，血糖指数较低，但大量摄入仍可能引起腹胀和腹泻。',
    warning: '',
    source: 'GB2760-2024 / JECFA第27次评估报告'
  },
  {
    id: 'e960',
    name: '甜菊糖苷',
    aliases: ['E960', '甜菊糖', 'Steviol Glycosides'],
    code: 'E960',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-4mg/kg体重',
    commonFoods: '饮料、酸奶、冰淇淋、桌面甜味剂',
    summary: '天然来源高倍甜味剂，零热量',
    detail: '甜菊糖苷从甜叶菊叶片中提取，甜度约为蔗糖的200-300倍，不产生热量。其在体内水解为甜菊醇后经肠道菌群代谢排出，不影响血糖水平，是糖尿病患者和控糖人群的优选甜味剂，但带有微苦后味。',
    warning: '',
    source: 'GB2760-2024 / JECFA第69次评估报告'
  },
  {
    id: 'e957',
    name: '索马甜',
    aliases: ['E957', '奇异果甜蛋白', 'Thaumatin'],
    code: 'E957',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、口香糖、乳制品、调味品',
    summary: '天然蛋白质甜味剂，甜度极高',
    detail: '索马甜从西非植物Thaumatococcus daniellii果实中提取，甜度约为蔗糖的2000-3000倍，是目前已知最甜的天然物质之一。作为蛋白质，在体内可完全消化为氨基酸，JECFA未设定ADI值，安全性极高。',
    warning: '',
    source: 'GB2760-2024 / JECFA第34次评估报告'
  },

  // ==================== 色素 ====================

  {
    id: 'e102',
    name: '柠檬黄',
    aliases: ['E102', '酒石黄', 'Tartrazine'],
    code: 'E102',
    category: '色素',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-7.5mg/kg体重',
    commonFoods: '饮料、糖果、果冻、冰淇淋',
    summary: '最常用的合成黄色素，南安普顿研究关联儿童多动',
    detail: '柠檬黄属偶氮类合成色素，着色力强、稳定性好。2007年南安普顿大学研究发现柠檬黄等六种色素与苯甲酸钠的混合物可能与儿童多动行为相关，欧盟随后要求含该色素的食品标注"可能对儿童活动和注意力产生不良影响"。',
    warning: '儿童应减少摄入，欧盟要求标注对儿童多动的潜在影响',
    source: 'GB2760-2024 / JECFA第11次评估报告 / 南安普顿研究2007'
  },
  {
    id: 'e110',
    name: '日落黄',
    aliases: ['E110', '晚霞黄', 'Sunset Yellow'],
    code: 'E110',
    category: '色素',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-3.5mg/kg体重',
    commonFoods: '饮料、糖果、果冻、调味品',
    summary: '常用合成橙色素，与儿童多动争议相关',
    detail: '日落黄属偶氮类合成色素，常与柠檬黄配合使用调色。与柠檬黄同属南安普顿研究涉及的六种色素之一，欧盟同样要求含日落黄的食品标注对儿童行为的潜在影响，挪威和芬兰曾一度禁止使用。',
    warning: '儿童应减少摄入，欧盟要求标注对儿童多动的潜在影响',
    source: 'GB2760-2024 / JECFA第11次评估报告 / 南安普顿研究2007'
  },
  {
    id: 'e124',
    name: '胭脂红',
    aliases: ['E124', '丽春红4R', 'Ponceau 4R'],
    code: 'E124',
    category: '色素',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '限量',
    usStatus: '禁止',
    adi: '0-4mg/kg体重',
    commonFoods: '饮料、糖果、果冻、糕点装饰',
    summary: '合成红色素，美国禁用，南安普顿六色素之一',
    detail: '胭脂红属偶氮类合成色素，着色力强但耐光性较差。美国FDA未批准其在食品中使用，欧盟虽允许但限制使用范围并要求标注对儿童行为的潜在影响。南安普顿研究将其列为可能影响儿童行为的六种色素之一。',
    warning: '美国禁用，儿童应减少摄入',
    source: 'GB2760-2024 / JECFA第11次评估报告 / 南安普顿研究2007'
  },
  {
    id: 'e123',
    name: '苋菜红',
    aliases: ['E123', 'Amaranth'],
    code: 'E123',
    category: '色素',
    safetyLevel: '慎用',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '禁止',
    adi: '0-0.5mg/kg体重',
    commonFoods: '饮料、糖果、山楂制品',
    summary: '合成红色素，多国限制或禁止，儿童应避免',
    detail: '苋菜红属偶氮类合成色素，早期动物实验显示高剂量可能增加大鼠肿瘤发生率，JECFA将ADI设定为极低的0-0.5mg/kg体重。美国自1976年起禁止在食品中使用，欧盟仅允许在少数酒精饮料中使用，中国限制使用范围且用量严格。',
    warning: '儿童和孕妇应避免含苋菜红的食品',
    source: 'GB2760-2024 / JECFA第13次评估报告'
  },
  {
    id: 'e127',
    name: '赤藓红',
    aliases: ['E127', '樱桃红', 'Erythrosine'],
    code: 'E127',
    category: '色素',
    safetyLevel: '争议',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '允许',
    adi: '0-0.1mg/kg体重',
    commonFoods: '鸡尾酒樱桃、糖果、烘焙装饰',
    summary: '合成红色素，ADI值极低，使用范围受限',
    detail: '赤藓红属氧杂蒽类色素，早期研究显示高剂量可能影响甲状腺功能，JECFA据此将ADI设定为极低的0-0.1mg/kg体重。欧盟仅允许用于鸡尾酒樱桃等极少数食品，中国也限制使用范围，但美国仍广泛允许使用。',
    warning: '甲状腺疾病患者应注意',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e129',
    name: '诱惑红',
    aliases: ['E129', 'Allura Red'],
    code: 'E129',
    category: '色素',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-7mg/kg体重',
    commonFoods: '饮料、糖果、冰淇淋、调味品',
    summary: '合成红色素，南安普顿研究涉及色素之一',
    detail: '诱惑红属偶氮类合成色素，是美国最常用的红色素替代品（替代美国禁用的苋菜红和胭脂红）。南安普顿研究将其列为可能影响儿童行为的色素之一，欧盟要求含诱惑红的食品标注警示信息。',
    warning: '儿童应减少摄入，欧盟要求标注对儿童多动的潜在影响',
    source: 'GB2760-2024 / JECFA第25次评估报告 / 南安普顿研究2007'
  },
  {
    id: 'e133',
    name: '亮蓝',
    aliases: ['E133', 'Brilliant Blue FCF'],
    code: 'E133',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-10mg/kg体重',
    commonFoods: '饮料、糖果、冰淇淋、糕点装饰',
    summary: '常用合成蓝色素，安全性较好',
    detail: '亮蓝属三苯甲烷类色素，着色力强，耐光耐热性较好，是食品工业中最常用的蓝色素。其毒理学数据较为充分，JECFA和各国监管机构均认为在规定用量下安全，南安普顿研究未将其列入有争议的色素名单。',
    warning: '',
    source: 'GB2760-2024 / JECFA第13次评估报告'
  },
  {
    id: 'e132',
    name: '靛蓝',
    aliases: ['E132', 'Indigotine'],
    code: 'E132',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-5mg/kg体重',
    commonFoods: '饮料、糖果、糕点装饰',
    summary: '合成靛蓝色素，安全性可接受',
    detail: '靛蓝属靛族色素，耐光性较差易褪色，常与亮蓝配合调色。其毒理学评价数据完整，JECFA设定的ADI值有一定安全余量，正常食用条件下安全性可接受，但使用量远少于亮蓝。',
    warning: '',
    source: 'GB2760-2024 / JECFA第13次评估报告'
  },
  {
    id: 'e160a',
    name: 'β-胡萝卜素',
    aliases: ['E160a', 'Beta-Carotene', 'β胡萝卜素'],
    code: 'E160a',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、奶油、黄油、烘焙食品',
    summary: '天然来源色素，兼具维生素A前体功能',
    detail: 'β-胡萝卜素广泛存在于胡萝卜、南瓜等蔬果中，既是天然黄色素也是维生素A的前体，在体内可按需转化为维生素A。JECFA未设定ADI值，食品级β-胡萝卜素无论来自天然提取还是合成，安全性均极高。',
    warning: '',
    source: 'GB2760-2024 / JECFA第41次评估报告'
  },
  {
    id: 'e150d',
    name: '焦糖色',
    aliases: ['E150d', '焦糖色素', 'Caramel Color IV'],
    code: 'E150d',
    category: '色素',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-200mg/kg体重',
    commonFoods: '可乐、酱油、醋、啤酒',
    summary: '最广泛使用的食用色素，IV类含4-MEI引发争议',
    detail: '焦糖色分为四类，其中亚硫酸铵法生产的IV类（E150d）在制造过程中产生副产物4-甲基咪唑（4-MEI），IARC将4-MEI列为2B类可能致癌物。虽然可乐中4-MEI含量极低，但加州65号提案要求标注警示，争议持续至今。',
    warning: '长期大量饮用含焦糖色IV类的可乐类饮料需注意',
    source: 'GB2760-2024 / JECFA第79次评估报告 / 加州65号提案'
  },
  {
    id: 'e141',
    name: '叶绿素铜钠盐',
    aliases: ['E141', 'Sodium Copper Chlorophyllin'],
    code: 'E141',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-15mg/kg体重',
    commonFoods: '饮料、糖果、果冻、糕点',
    summary: '天然来源绿色素，稳定性优于天然叶绿素',
    detail: '叶绿素铜钠盐以天然叶绿素为原料，用铜离子取代镁离子制成，显著提高了耐光耐热稳定性。铜离子以螯合态存在，不会被人体吸收游离铜，安全性良好，是绿色食品着色的首选。',
    warning: '',
    source: 'GB2760-2024 / JECFA第13次评估报告'
  },
  {
    id: 'monascus-red',
    name: '红曲红',
    aliases: ['红曲色素', 'Monascus Red'],
    code: '—',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '禁止',
    usStatus: '禁止',
    adi: 'ADI未规定',
    commonFoods: '肉制品、豆腐乳、调味品、糕点',
    summary: '中国传统天然红色素，欧美暂未批准食品使用',
    detail: '红曲红由红曲霉发酵大米产生，是中国传统食品着色剂，已有千年使用历史。其安全性在中国和日本得到充分验证，但欧盟和美国因红曲霉可能同时产生桔霉素而未批准食品使用，中国国标对桔霉素含量有严格限量。',
    warning: '',
    source: 'GB2760-2024 / 中国药典'
  },
  {
    id: 'e160c',
    name: '辣椒红',
    aliases: ['E160c', 'Paprika Extract'],
    code: 'E160c',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '肉制品、调味品、火锅底料、酱料',
    summary: '天然辣椒提取物，安全性极高',
    detail: '辣椒红从辣椒中提取，主要成分为辣椒红素和辣椒玉红素，着色力强且耐热性好。作为天然色素，JECFA未设定ADI值，广泛用于肉制品和调味品中，兼具增色和增香效果。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e162',
    name: '甜菜红',
    aliases: ['E162', 'Beetroot Red', '甜菜根红'],
    code: 'E162',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、酸奶、冰淇淋、糖果',
    summary: '天然红色素，色泽鲜艳安全性高',
    detail: '甜菜红从甜菜根中提取，主要成分为甜菜苷，呈鲜艳的紫红色。作为天然色素，JECFA未设定ADI值，但其耐热性较差，在高温和光照下易褪色，更适合冷饮和乳制品使用。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'gardenia-yellow',
    name: '栀子黄',
    aliases: ['栀子黄色素', 'Gardenia Yellow'],
    code: '—',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面制品、糕点、饮料、糖果',
    summary: '天然黄色素，中国和日本广泛使用',
    detail: '栀子黄从栀子果实中提取，主要成分为藏红花素和藏红花酸，着色力强且耐光耐热性较好。在中国和日本有长期使用历史，安全性良好，但欧盟仅批准栀子蓝，栀子黄在欧盟的使用尚在评估中。',
    warning: '',
    source: 'GB2760-2024 / 日本食品添加物公定书'
  },

  // ==================== 增稠剂 ====================

  {
    id: 'e415',
    name: '黄原胶',
    aliases: ['E415', '汉生胶', 'Xanthan Gum'],
    code: 'E415',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、酱料、冰淇淋、沙拉酱',
    summary: '最常用的食品增稠剂，安全性极高',
    detail: '黄原胶由野油菜黄单胞菌发酵产生，具有优异的增稠、悬浮和乳化稳定功能，在低浓度下即可形成高粘度溶液。其耐酸、耐盐、耐高温的特性使其成为食品工业中用途最广的增稠剂，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e466',
    name: '羧甲基纤维素钠',
    aliases: ['E466', 'CMC-Na', 'Sodium Carboxymethyl Cellulose'],
    code: 'E466',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '冰淇淋、饮料、果冻、面制品',
    summary: '常用增稠稳定剂，安全性良好',
    detail: '羧甲基纤维素钠由纤维素经化学改性制得，具有良好的增稠、保水和乳化稳定功能。在人体内不被消化吸收，以原形排出体外，JECFA未设定ADI值，广泛用于冰淇淋和饮料中改善口感。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e407',
    name: '卡拉胶',
    aliases: ['E407', '鹿角菜胶', 'Carrageenan'],
    code: 'E407',
    category: '增稠剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '冰淇淋、果冻、肉制品、巧克力奶',
    summary: '天然海藻胶，降解型卡拉胶的肠道安全性存争议',
    detail: '卡拉胶从红藻中提取，分为κ、ι、λ三种类型，具有优异的凝胶和增稠性能。争议焦点在于降解型卡拉胶（分子量低于食品级）在动物实验中显示可引起肠道炎症和溃疡，但食品级卡拉胶分子量大，不被肠道吸收，JECFA认为食品级产品安全。',
    warning: '消化系统敏感者建议适量',
    source: 'GB2760-2024 / JECFA第79次评估报告'
  },
  {
    id: 'e440',
    name: '果胶',
    aliases: ['E440', 'Pectin'],
    code: 'E440',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '果酱、果冻、酸奶、糖果',
    summary: '天然水果提取物，安全性极高',
    detail: '果胶天然存在于水果细胞壁中，以柑橘皮和苹果渣为原料提取。高甲氧基果胶在酸性高糖条件下形成凝胶（制果酱），低甲氧基果胶可与钙离子交联凝胶（低糖果冻）。JECFA未设定ADI值，是膳食纤维的良好来源。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'gelatin',
    name: '明胶',
    aliases: ['Gelatin', '食用明胶'],
    code: '—',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '果冻、软糖、酸奶、胶囊',
    summary: '动物胶原蛋白水解产物，安全性高',
    detail: '明胶由猪皮、牛骨等动物结缔组织中的胶原蛋白经酸或碱水解制得，在温水中溶解、冷却后形成凝胶。作为蛋白质类增稠剂，在体内可完全消化吸收，JECFA未设定ADI值，但需注意宗教和素食饮食限制。',
    warning: '',
    source: 'GB2760-2024 / JECFA评估报告'
  },
  {
    id: 'e406',
    name: '琼脂',
    aliases: ['E406', 'Agar', '琼胶'],
    code: 'E406',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '果冻、凉粉、糖果、微生物培养基',
    summary: '海藻提取物，传统凝胶剂',
    detail: '琼脂从红藻类石花菜等海藻中提取，由琼脂糖和琼脂胶组成。其凝胶强度高、凝固点与熔点差距大（凝胶在40°C以下凝固，85°C以上才熔化），使口感独特。不被人体消化酶分解，作为膳食纤维排出体外。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e401',
    name: '海藻酸钠',
    aliases: ['E401', 'Sodium Alginate', '褐藻酸钠'],
    code: 'E401',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '冰淇淋、酱料、仿生食品、面条',
    summary: '天然海藻胶，可形成钙凝胶',
    detail: '海藻酸钠从褐藻中提取，与钙离子反应可形成热不可逆凝胶，这一特性被广泛用于仿生食品（如仿鱼子酱）的制作。在体内不消化吸收，JECFA未设定ADI值，兼具增稠和膳食纤维功能。',
    warning: '',
    source: 'GB2760-2024 / JECFA第13次评估报告'
  },
  {
    id: 'e412',
    name: '瓜尔胶',
    aliases: ['E412', 'Guar Gum', '瓜耳胶'],
    code: 'E412',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '冰淇淋、酱料、烘焙食品、饮料',
    summary: '豆科植物胶，增稠效率极高',
    detail: '瓜尔胶从瓜尔豆胚乳中提取，是天然胶中增稠效率最高的品种，低浓度即可产生高粘度。其耐酸性和耐剪切性优于许多其他胶体，与黄原胶复配使用可产生协同增稠效应，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第19次评估报告'
  },
  {
    id: 'e410',
    name: '刺槐豆胶',
    aliases: ['E410', 'Locust Bean Gum', '角豆胶'],
    code: 'E410',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '冰淇淋、奶酪、肉制品、酱料',
    summary: '天然植物胶，与卡拉胶复配效果佳',
    detail: '刺槐豆胶从角豆树种子胚乳中提取，单独使用仅增稠不凝胶，但与卡拉胶或黄原胶复配时可产生显著的协同凝胶效应，广泛用于冰淇淋改善质地和抗融化。JECFA未设定ADI值，安全性极高。',
    warning: '',
    source: 'GB2760-2024 / JECFA第19次评估报告'
  },
  {
    id: 'e418',
    name: '结冷胶',
    aliases: ['E418', 'Gellan Gum'],
    code: 'E418',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '果冻、饮料、甜品、素肉',
    summary: '微生物发酵胶，凝胶透明度极高',
    detail: '结冷胶由少动鞘脂单胞菌发酵产生，可形成极其透明且口感脆弹的凝胶，是制作仿生水果和透明果冻的理想胶体。低酰基型形成硬脆凝胶，高酰基型形成柔软弹性凝胶，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第51次评估报告'
  },

  // ==================== 乳化剂 ====================

  {
    id: 'e322',
    name: '大豆磷脂',
    aliases: ['E322', '卵磷脂', 'Soy Lecithin'],
    code: 'E322',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '巧克力、面包、奶粉、人造奶油',
    summary: '天然乳化剂，兼具营养功能',
    detail: '大豆磷脂从大豆油脱胶过程中提取，主要成分为磷脂酰胆碱、磷脂酰乙醇胺等。其两亲分子结构（亲水基和亲油基）使其成为优良的天然乳化剂，同时是细胞膜的重要组成部分和胆碱的来源，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e473',
    name: '蔗糖脂肪酸酯',
    aliases: ['E473', '蔗糖酯', 'Sucrose Esters of Fatty Acids'],
    code: 'E473',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-30mg/kg体重',
    commonFoods: '面包、蛋糕、饮料、口香糖',
    summary: 'HLB值范围宽的乳化剂，用途广泛',
    detail: '蔗糖脂肪酸酯由蔗糖与脂肪酸酯化制得，通过调整脂肪酸链长和酯化度可获得HLB值从1到16的系列产品，覆盖从水包油到油包水的全范围乳化需求。在体内可水解为蔗糖和脂肪酸正常代谢，安全性良好。',
    warning: '',
    source: 'GB2760-2024 / JECFA第73次评估报告'
  },
  {
    id: 'e471',
    name: '单双甘油脂肪酸酯',
    aliases: ['E471', '单甘酯', 'Mono- and Diglycerides of Fatty Acids'],
    code: 'E471',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面包、蛋糕、冰淇淋、人造奶油',
    summary: '最常用的食品乳化剂，安全性极高',
    detail: '单双甘油脂肪酸酯由食用油脂与甘油酯化制得，在体内可完全水解为甘油和脂肪酸参与正常代谢，JECFA未设定ADI值。其优良的乳化、抗淀粉老化功能使其成为面包和烘焙食品中最常用的品质改良剂。',
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'e433',
    name: '聚山梨醇酯80',
    aliases: ['E433', '吐温80', 'Polysorbate 80'],
    code: 'E433',
    category: '乳化剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-25mg/kg体重',
    commonFoods: '冰淇淋、沙拉酱、调味品、饮料',
    summary: '高效乳化剂，肠道菌群影响引发争议',
    detail: '聚山梨醇酯80是非离子型表面活性剂，乳化能力极强，少量即可稳定乳液体系。争议来自部分研究显示其可能改变肠道菌群组成和增加肠道通透性，但这些研究多使用远高于食品用量的浓度，实际食品暴露量下的风险尚不明确。',
    warning: '肠道敏感者建议适量',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'e481',
    name: '硬脂酰乳酸钠',
    aliases: ['E481', 'SSL', 'Sodium Stearoyl Lactylate'],
    code: 'E481',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-20mg/kg体重',
    commonFoods: '面包、馒头、面条、糕点',
    summary: '面制品品质改良剂，增强面筋网络',
    detail: '硬脂酰乳酸钠兼具乳化和面筋强化功能，可与面筋蛋白形成复合物增强面团弹性和持气性，同时与淀粉络合延缓老化。在体内水解为硬脂酸和乳酸正常代谢，是面包和馒头中最常用的品质改良剂之一。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e482',
    name: '硬脂酰乳酸钙',
    aliases: ['E482', 'CSL', 'Calcium Stearoyl Lactylate'],
    code: 'E482',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-20mg/kg体重',
    commonFoods: '面包、馒头、糕点',
    summary: '面制品改良剂，功能与SSL类似',
    detail: '硬脂酰乳酸钙的功能与硬脂酰乳酸钠相似，均可增强面筋网络和延缓淀粉老化，但钙离子形式在某些配方中表现更优。两者常配合使用，在体内水解为硬脂酸、乳酸和钙离子正常代谢。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e472e',
    name: '双乙酰酒石酸单双甘油酯',
    aliases: ['E472e', 'DATEM', 'Diacetyl Tartaric Acid Esters'],
    code: 'E472e',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-50mg/kg体重',
    commonFoods: '面包、馒头、蛋糕、面条',
    summary: '高效面筋增强剂，面包体积增大效果显著',
    detail: '双乙酰酒石酸单双甘油酯（DATEM）是面筋增强效果最显著的乳化剂之一，可与面筋蛋白形成强复合物，显著增加面包体积和改善内部结构。在体内水解为甘油、脂肪酸、酒石酸和醋酸，均为正常代谢产物。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e491',
    name: '山梨醇酐单硬脂酸酯',
    aliases: ['E491', '司盘60', 'Sorbitan Monostearate'],
    code: 'E491',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-25mg/kg体重',
    commonFoods: '蛋糕、冰淇淋、巧克力、饮料',
    summary: '亲油性乳化剂，常与吐温配合使用',
    detail: '山梨醇酐单硬脂酸酯（司盘60）是亲油性乳化剂，HLB值约4.7，适合油包水型乳液。常与亲水性的聚山梨醇酯（吐温）复配使用，通过调整两者比例可适应不同乳化体系的需求，在体内水解为山梨醇和硬脂酸正常代谢。',
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },

  // ==================== 抗氧化剂 ====================

  {
    id: 'e319',
    name: '特丁基对苯二酚',
    aliases: ['E319', 'TBHQ', 'Tertiary Butylhydroquinone'],
    code: 'E319',
    category: '抗氧化剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '禁止',
    usStatus: '允许',
    adi: '0-0.7mg/kg体重',
    commonFoods: '食用油、油炸食品、方便面、坚果',
    summary: '高效合成抗氧化剂，欧盟禁用',
    detail: 'TBHQ通过提供氢原子终止油脂自动氧化的自由基链式反应，抗氧化效率极高，尤其对植物油效果显著。争议在于高剂量动物实验显示可能引起DNA损伤和促进肿瘤发生，欧盟因此未批准其在食品中使用，但JECFA认为在ADI范围内安全。',
    warning: '欧盟禁用，建议减少油炸食品摄入',
    source: 'GB2760-2024 / JECFA第19次评估报告 / EFSA评估意见'
  },
  {
    id: 'e320',
    name: '丁基羟基茴香醚',
    aliases: ['E320', 'BHA', 'Butylated Hydroxyanisole'],
    code: 'E320',
    category: '抗氧化剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-0.5mg/kg体重',
    commonFoods: '食用油、黄油、谷物制品、零食',
    summary: '常用合成抗氧化剂，IARC列为2B类致癌物',
    detail: 'BHA通过捕获自由基中断油脂氧化链式反应，对动物油脂抗氧化效果优于植物油。IARC基于大鼠前胃肿瘤证据将其列为2B类可能致癌物，但人类无前胃解剖结构，且该效应存在剂量阈值，JECFA维持ADI但降低了数值。',
    warning: '建议减少含BHA的加工食品摄入',
    source: 'GB2760-2024 / JECFA第44次评估报告 / IARC评估'
  },
  {
    id: 'e321',
    name: '二丁基羟基甲苯',
    aliases: ['E321', 'BHT', 'Butylated Hydroxytoluene'],
    code: 'E321',
    category: '抗氧化剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-0.3mg/kg体重',
    commonFoods: '食用油、谷物制品、口香糖、零食',
    summary: '常用合成抗氧化剂，安全性争议持续',
    detail: 'BHT通过提供氢原子淬灭过氧自由基发挥抗氧化作用，与BHA常复配使用产生协同效应。争议来自动物实验中高剂量BHT可引起肝脏肿大和酶诱导效应，日本和罗马尼亚曾限制其在食品中使用，JECFA将ADI设定为较低的0-0.3mg/kg体重。',
    warning: '建议减少含BHT的加工食品摄入',
    source: 'GB2760-2024 / JECFA第44次评估报告'
  },
  {
    id: 'e310',
    name: '没食子酸丙酯',
    aliases: ['E310', 'PG', 'Propyl Gallate'],
    code: 'E310',
    category: '抗氧化剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-1.4mg/kg体重',
    commonFoods: '食用油、坚果、谷物制品',
    summary: '合成抗氧化剂，与BHA/BHT复配使用',
    detail: '没食子酸丙酯通过清除自由基和螯合金属离子双重机制抗氧化，与BHA和BHT复配时具有显著协同效应。争议在于其可能具有弱雌激素活性和致敏性，部分人群接触后可出现接触性皮炎，JECFA设定了中等ADI值。',
    warning: '敏感体质者注意可能的过敏反应',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e306',
    name: '维生素E',
    aliases: ['E306', '生育酚', 'Tocopherol'],
    code: 'E306',
    category: '抗氧化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '食用油、坚果、谷物制品、婴幼儿食品',
    summary: '天然抗氧化剂，兼具营养功能',
    detail: '维生素E（生育酚混合物）从大豆油等植物油中提取，通过捕获脂质过氧自由基中断氧化链式反应，是生物膜上最重要的脂溶性抗氧化剂。作为人体必需营养素，JECFA未设定ADI值，食品中使用既抗氧化又补充营养。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e300',
    name: '维生素C',
    aliases: ['E300', '抗坏血酸', 'Ascorbic Acid'],
    code: 'E300',
    category: '抗氧化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、果汁、肉制品、罐头',
    summary: '天然抗氧化剂，人体必需营养素',
    detail: '维生素C通过还原作用清除氧自由基和再生其他抗氧化剂（如维生素E），在水相体系中抗氧化效果显著。作为人体必需营养素参与胶原蛋白合成和免疫功能，JECFA未设定ADI值，但大剂量补充可能引起腹泻。',
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'e316',
    name: '异抗坏血酸钠',
    aliases: ['E316', '异维C钠', 'Sodium Erythorbate'],
    code: 'E316',
    category: '抗氧化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '肉制品、罐头、果蔬制品',
    summary: '维生素C的异构体，抗氧化性优但无营养活性',
    detail: '异抗坏血酸钠是L-抗坏血酸（维生素C）的D-异构体，抗氧化能力与维生素C相当，但不具备维生素C的营养活性（人体不能利用）。其成本低于维生素C，在肉制品中广泛用于护色和抗氧化，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'tea-polyphenol',
    name: '茶多酚',
    aliases: ['Tea Polyphenols', '绿茶提取物'],
    code: '—',
    category: '抗氧化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '食用油、肉制品、糕点、饮料',
    summary: '天然茶提取物，抗氧化和保健功能兼备',
    detail: '茶多酚从绿茶中提取，主要活性成分为儿茶素类（EGCG等），通过提供酚羟基氢原子捕获自由基实现抗氧化，抗氧化能力远强于维生素C和维生素E。兼具抑菌和除臭功能，是中国特有的天然食品抗氧化剂。',
    warning: '',
    source: 'GB2760-2024 / 中国药典'
  },

  // ==================== 酸度调节剂 ====================

  {
    id: 'e330',
    name: '柠檬酸',
    aliases: ['E330', 'Citric Acid'],
    code: 'E330',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、糖果、果酱、罐头',
    summary: '最常用的食品酸味剂，安全性极高',
    detail: '柠檬酸是三羧酸循环的中间产物，天然存在于柑橘类水果中，是人体正常代谢的组成部分。其酸味柔和爽口，兼具螯合金属离子、增强抗氧化和抑菌功能，JECFA未设定ADI值，是食品工业中使用量最大的酸味剂。',
    warning: '',
    source: 'GB2760-2024 / JECFA第13次评估报告'
  },
  {
    id: 'e331',
    name: '柠檬酸钠',
    aliases: ['E331', 'Sodium Citrate'],
    code: 'E331',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、肉制品、奶酪、果冻',
    summary: '柠檬酸的钠盐，兼具缓冲和乳化功能',
    detail: '柠檬酸钠在水中呈弱碱性，常与柠檬酸配合使用构成缓冲体系，精确控制食品pH值。在奶酪制作中促进乳化，在肉制品中增强保水性，在饮料中改善口感，JECFA未设定ADI值，安全性极高。',
    warning: '',
    source: 'GB2760-2024 / JECFA第13次评估报告'
  },
  {
    id: 'e500',
    name: '碳酸钠',
    aliases: ['E500', '纯碱', 'Sodium Carbonate'],
    code: 'E500',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面制品、糕点、酱油',
    summary: '常用碱性调节剂，面制品中改善质地',
    detail: '碳酸钠在水中呈强碱性，在面制品中可增强面筋弹性和延展性，使面条口感更筋道。在酱油生产中用于中和发酵产生的有机酸，在糕点中与酸性物质反应产生二氧化碳起膨松作用，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'e500ii',
    name: '碳酸氢钠',
    aliases: ['E500ii', '小苏打', 'Sodium Bicarbonate'],
    code: 'E500ii',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面包、蛋糕、饼干、饮料',
    summary: '最常用的膨松剂和酸度调节剂',
    detail: '碳酸氢钠受热或遇酸分解放出二氧化碳，兼具膨松和调节酸度的双重功能。在烘焙中与酸性物质配合产生气体使制品蓬松，在饮料中调节酸度，在肉制品中改善色泽，JECFA未设定ADI值，安全性极高。',
    warning: '',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'e270',
    name: '乳酸',
    aliases: ['E270', 'Lactic Acid'],
    code: 'E270',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '酸奶、饮料、糖果、肉制品',
    summary: '天然有机酸，人体自身代谢产物',
    detail: '乳酸是糖酵解的终产物，人体肌肉运动时即产生乳酸。食品级乳酸可由乳酸菌发酵制得，酸味温和具有鲜味感，在肉制品中兼具防腐和护色功能，JECFA未设定ADI值，是安全性最高的酸味剂之一。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e296',
    name: '苹果酸',
    aliases: ['E296', 'Malic Acid'],
    code: 'E296',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、糖果、果酱、口香糖',
    summary: '天然有机酸，酸味清鲜持久',
    detail: '苹果酸天然存在于苹果等水果中，也是三羧酸循环的中间产物。其酸味比柠檬酸更清爽持久，在后味上表现更佳，常与柠檬酸复配使用改善口感层次，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e338',
    name: '磷酸',
    aliases: ['E338', 'Phosphoric Acid'],
    code: 'E338',
    category: '酸度调节剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-70mg/kg体重',
    commonFoods: '可乐饮料、肉制品、奶酪',
    summary: '可乐类饮料的主要酸味剂，过量摄入影响钙代谢',
    detail: '磷酸提供可乐特有的爽利酸味，也是肉制品和奶酪中重要的保水和乳化盐成分。争议在于高磷摄入可干扰钙磷平衡，影响骨密度，长期大量饮用含磷酸的碳酸饮料与骨质疏松风险增加相关，尤其对青少年骨骼发育有潜在影响。',
    warning: '青少年和骨质疏松风险人群应控制含磷酸饮料的摄入',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e297',
    name: '富马酸',
    aliases: ['E297', 'Fumaric Acid', '延胡索酸'],
    code: 'E297',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-6mg/kg体重',
    commonFoods: '饮料、糖果、果冻、烘焙食品',
    summary: '酸味最强的食品酸味剂，溶解度低释放缓慢',
    detail: '富马酸是三羧酸循环的中间产物，酸味强度约为柠檬酸的1.5倍，但水溶性低使其在食品中释放缓慢，酸味持久且不易产生过酸感。在烘焙食品中兼具膨松剂酸源功能，ADI值有一定限制但正常食用远不会超标。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },

  // ==================== 膨松剂 ====================

  {
    id: 'e503',
    name: '碳酸氢铵',
    aliases: ['E503', '臭粉', 'Ammonium Bicarbonate'],
    code: 'E503',
    category: '膨松剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饼干、桃酥、蛋糕',
    summary: '传统膨松剂，加热后完全分解无残留',
    detail: '碳酸氢铵受热后完全分解为氨气、二氧化碳和水，三者均为气体无残留，使制品内部形成均匀气孔。其膨松效果强于小苏打，但氨气味重，仅适用于薄型烘焙食品（如饼干）使氨气能充分挥发，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'e522',
    name: '硫酸铝钾',
    aliases: ['E522', '明矾', 'Potassium Aluminium Sulfate'],
    code: 'E522',
    category: '膨松剂',
    safetyLevel: '争议',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '限量',
    adi: '0-1mg/kg体重(以铝计)',
    commonFoods: '油条、粉丝、海蜇、膨化食品',
    summary: '传统膨松剂，铝残留是主要健康顾虑',
    detail: '硫酸铝钾（明矾）在面制品中与碳酸氢钠反应产生二氧化碳起膨松作用，同时使粉丝等制品口感更筋道。争议在于铝的神经毒性，长期高铝摄入与阿尔茨海默病风险相关，中国已禁止含铝食品添加剂在馒头等发酵面制品中使用。',
    warning: '儿童应减少含铝膨松剂的油条和膨化食品摄入',
    source: 'GB2760-2024 / JECFA第67次评估报告'
  },
  {
    id: 'e336',
    name: '酒石酸氢钾',
    aliases: ['E336', 'Cream of Tartar', '塔塔粉'],
    code: 'E336',
    category: '膨松剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-30mg/kg体重',
    commonFoods: '蛋糕、饼干、糖果',
    summary: '天然膨松酸源，蛋白霜稳定剂',
    detail: '酒石酸氢钾是葡萄酒酿造的副产物，在烘焙中作为泡打粉的酸性成分与小苏打反应产气。在蛋白霜制作中可稳定蛋白泡沫防止消泡，是制作天使蛋糕和马卡龙的关键原料，安全性良好。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'baking-powder',
    name: '泡打粉',
    aliases: ['Baking Powder', '发粉'],
    code: '—',
    category: '膨松剂',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '视配方而定',
    commonFoods: '蛋糕、饼干、油条、包子',
    summary: '复合膨松剂，含铝配方需注意',
    detail: '泡打粉是由碱性剂（小苏打）、酸性剂（酒石酸/磷酸盐/明矾）和填充剂（淀粉）组成的复合膨松剂。争议在于部分泡打粉使用硫酸铝钾/铵作为酸性剂，导致制品铝残留超标，中国已推广无铝泡打粉，含铝泡打粉在部分面制品中已被禁止。',
    warning: '选择无铝泡打粉，儿童应减少含铝泡打粉制作的食品',
    source: 'GB2760-2024 / 国家卫计委公告'
  },
  {
    id: 'e450i',
    name: '酸性焦磷酸钠',
    aliases: ['E450i', 'SAPP', 'Disodium Dihydrogen Pyrophosphate'],
    code: 'E450i',
    category: '膨松剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-70mg/kg体重',
    commonFoods: '蛋糕、面包、肉制品、海鲜',
    summary: '缓释型膨松酸源，适合冷冻面团',
    detail: '酸性焦磷酸钠在水中缓慢水解产生磷酸，与小苏打反应释放二氧化碳的速度较慢，适合需要延迟膨松的冷冻面团和预制烘焙食品。在肉制品中还兼具保水和护色功能，ADI值与磷酸盐类共享计算。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },

  // ==================== 稳定剂/其他 ====================

  {
    id: 'e621',
    name: '味精',
    aliases: ['E621', '谷氨酸钠', 'Monosodium Glutamate'],
    code: 'E621',
    category: '其他',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '调味品、方便面、零食、餐饮菜肴',
    summary: '最常用的鲜味剂，"中餐馆综合征"争议未消',
    detail: '味精通过激活舌上鲜味受体（T1R1/T1R3）产生鲜味，鲜味强度约为食盐的10倍。"中餐馆综合征"指部分人食用后出现头痛、面部麻木等症状，但双盲对照研究未能证实味精与这些症状的因果关系，JECFA未设定ADI值。',
    warning: '对味精敏感者可选择不添加',
    source: 'GB2760-2024 / JECFA第14次评估报告 / FASEB报告1995'
  },
  {
    id: 'e635',
    name: "5'-呈味核苷酸二钠",
    aliases: ['E635', 'I+G', 'Disodium 5-Ribonucleotides'],
    code: 'E635',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '调味品、方便面、零食、酱油',
    summary: '与味精协同增鲜的核苷酸类鲜味剂',
    detail: "5'-呈味核苷酸二钠由肌苷酸二钠（IMP）和鸟苷酸二钠（GMP）混合组成，与味精复配使用时可产生8-30倍的协同增鲜效应。核苷酸是RNA的基本组成单位，在体内正常代谢，JECFA未设定ADI值。",
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'e631',
    name: '肌苷酸二钠',
    aliases: ['E631', 'IMP', 'Disodium Inosinate'],
    code: 'E631',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '调味品、方便面、零食、肉制品',
    summary: '天然核苷酸鲜味剂，与味精协同增鲜',
    detail: '肌苷酸二钠天然存在于柴鱼片和鸡肉中，是鲜味的重要来源。与味精复配时产生显著的协同增鲜效应，少量即可大幅提升整体鲜味强度。肌苷酸是嘌呤代谢的中间产物，在体内正常代谢，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'e551',
    name: '二氧化硅',
    aliases: ['E551', 'Silicon Dioxide', '白炭黑'],
    code: 'E551',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '奶粉、调味粉、速溶咖啡、片剂',
    summary: '抗结剂，防止粉状食品结块',
    detail: '食品级二氧化硅为无定形结构（非结晶型），通过吸附在粉体颗粒表面形成隔离层防止结块，不影响人体吸收。与结晶型二氧化硅（石棉状）不同，无定形二氧化硅不被肺部巨噬细胞吞噬，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e508',
    name: '氯化钾',
    aliases: ['E508', 'Potassium Chloride'],
    code: 'E508',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '低钠盐、运动饮料、功能饮料',
    summary: '食盐替代品，减钠不减咸',
    detail: '氯化钾的咸度约为氯化钠的70%，在低钠盐中替代部分食盐以减少钠摄入。钾离子是人体必需电解质，参与神经传导和心肌功能，但肾功能不全者排钾能力下降，需在医生指导下控制钾摄入量。',
    warning: '肾功能不全者需谨慎使用含氯化钾的食品',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'hydrogenated-oil',
    name: '氢化植物油',
    aliases: ['Hydrogenated Vegetable Oil', '植物奶油', '人造奶油'],
    code: '—',
    category: '其他',
    safetyLevel: '慎用',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '禁止',
    adi: '未制定',
    commonFoods: '奶油蛋糕、植脂末、代可可脂巧克力、饼干',
    summary: '含反式脂肪酸，心血管健康风险明确',
    detail: '氢化植物油通过催化加氢将液态植物油转化为固态或半固态脂肪，过程中产生反式脂肪酸。反式脂肪酸升高LDL胆固醇同时降低HDL胆固醇，心血管危害甚至超过饱和脂肪，WHO建议消除食品中工业生产的反式脂肪酸，美国已禁止部分氢化油在食品中使用。',
    warning: '儿童和心血管疾病患者应避免含氢化植物油的食品，关注配料表中"代可可脂""植脂末"等标识',
    source: 'GB2760-2024 / WHO反式脂肪酸消除指南 / FDA 2018禁令'
  },
  {
    id: 'hfcs',
    name: '果葡糖浆',
    aliases: ['High Fructose Corn Syrup', 'HFCS', '高果糖浆'],
    code: '—',
    category: '其他',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '限量',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、冰淇淋、果酱、烘焙食品',
    summary: '常用甜味剂，过量果糖摄入与代谢疾病相关',
    detail: '果葡糖浆由淀粉酶解和异构化制得，含果糖和葡萄糖，F42型含果糖42%、F55型含55%。争议在于果糖的代谢途径不同于葡萄糖——主要在肝脏代谢，过量摄入可促进脂肪合成和尿酸生成，与非酒精性脂肪肝、痛风和胰岛素抵抗风险增加相关。',
    warning: '控制含果葡糖浆饮料的摄入量，痛风和高尿酸人群特别注意',
    source: 'GB2760-2024 / WHO限糖指南'
  },
  {
    id: 'maltodextrin',
    name: '麦芽糊精',
    aliases: ['Maltodextrin', '麦芽糊精'],
    code: '—',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '奶粉、速溶食品、调味品、运动营养品',
    summary: '淀粉水解产物，增稠和载体功能',
    detail: '麦芽糊精由淀粉经酶法低度水解制得，DE值低于20，介于淀粉和麦芽糖之间。其溶解性好、甜度低、增稠性温和，广泛用作速溶食品的载体和脂肪替代品。在体内消化吸收与淀粉相同，血糖指数接近麦芽糖。',
    warning: '',
    source: 'GB2760-2024 / JECFA评估报告'
  },
  {
    id: 'e460i',
    name: '微晶纤维素',
    aliases: ['E460i', 'MCC', 'Microcrystalline Cellulose'],
    code: 'E460i',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '冰淇淋、沙拉酱、片剂、代餐食品',
    summary: '纤维素衍生物，零热量膳食纤维',
    detail: '微晶纤维素由天然纤维素经酸水解制得，去除无定形区保留结晶区，形成微小纤维颗粒。其不溶于水但可吸水膨胀，兼具增稠、抗结和膳食纤维功能，不被人体消化酶分解，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e1200',
    name: '聚葡萄糖',
    aliases: ['E1200', 'Polydextrose'],
    code: 'E1200',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '低糖食品、饮料、乳制品、烘焙食品',
    summary: '水溶性膳食纤维，兼具增稠和低热量甜味',
    detail: '聚葡萄糖由葡萄糖、山梨醇和柠檬酸缩聚制得，是1kcal/g的低热量水溶性膳食纤维。其甜度仅为蔗糖的10%，可替代部分糖和脂肪改善食品质地，同时具有益生元功能促进肠道双歧杆菌生长，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第51次评估报告'
  },

  // ==================== 补充添加剂 ====================

  {
    id: 'e281',
    name: '丙酸钠',
    aliases: ['E281', 'Sodium Propionate'],
    code: 'E281',
    category: '防腐剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面包、糕点、果酱',
    summary: '与丙酸钙同类的安全防腐剂',
    detail: '丙酸钠与丙酸钙功能相同，通过抑制霉菌生长发挥防腐作用，在体内代谢为丙酸参与正常脂肪酸代谢。钠盐形式更易溶于水，适合液体食品使用，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  },
  {
    id: 'e262ii',
    name: '双乙酸钠',
    aliases: ['E262ii', 'SDA', 'Sodium Diacetate'],
    code: 'E262ii',
    category: '防腐剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面包、肉制品、调味品、酱菜',
    summary: '醋酸类防腐剂，兼具防腐和调味功能',
    detail: '双乙酸钠是醋酸与醋酸钠的复合物，在食品中缓慢释放醋酸抑制霉菌和细菌生长。其醋酸味可增强食品风味，兼具防腐和调味双重功能，在体内代谢为醋酸和钠离子，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e235',
    name: '纳他霉素',
    aliases: ['E235', 'Natamycin', '游霉素'],
    code: 'E235',
    category: '防腐剂',
    safetyLevel: '安全',
    gbStatus: '限量',
    euStatus: '限量',
    usStatus: '允许',
    adi: '0-0.3mg/kg体重',
    commonFoods: '奶酪、肉制品表面、酸奶',
    summary: '天然抗真菌素，仅用于食品表面防腐',
    detail: '纳他霉素由纳塔尔链霉菌产生，专一性抑制真菌和酵母菌，对细菌无效。其仅用于食品表面喷涂，不渗透入食品内部，因此摄入量极低。JECFA设定了较低的ADI值，但实际暴露量远低于此值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第51次评估报告'
  },
  {
    id: 'e956',
    name: '阿力甜',
    aliases: ['E956', 'Alitame'],
    code: 'E956',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '禁止',
    usStatus: '允许',
    adi: '0-1mg/kg体重',
    commonFoods: '饮料、口香糖、甜品',
    summary: '高倍甜味剂，甜度约为蔗糖2000倍',
    detail: '阿力甜属二肽类甜味剂，甜度约为蔗糖的2000倍，口感优于阿斯巴甜且热稳定性更好。欧盟因安全性数据不充分未批准使用，但JECFA和FDA均认为安全，中国允许在限量范围内使用。',
    warning: '',
    source: 'GB2760-2024 / JECFA第46次评估报告'
  },
  {
    id: 'e961',
    name: '纽甜',
    aliases: ['E961', 'Neotame'],
    code: 'E961',
    category: '甜味剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-2mg/kg体重',
    commonFoods: '饮料、酸奶、口香糖、烘焙食品',
    summary: '阿斯巴甜衍生物，甜度更高安全性更好',
    detail: '纽甜是阿斯巴甜的衍生物，甜度约为蔗糖的7000-13000倍，是阿斯巴甜的30-60倍。其3,3-二甲基丁基基团增强了与甜味受体的结合力，同时不被肽酶水解，因此苯丙酮尿症患者可安全使用。',
    warning: '',
    source: 'GB2760-2024 / JECFA第61次评估报告'
  },
  {
    id: 'e120',
    name: '紫胶红',
    aliases: ['E120', 'Lac Dye', '虫胶红'],
    code: 'E120',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-5mg/kg体重',
    commonFoods: '饮料、糖果、果冻、糕点',
    summary: '昆虫来源天然红色素，素食者需注意',
    detail: '紫胶红从紫胶虫分泌的树脂中提取，主要成分为紫胶色酸，呈鲜艳的红色。作为天然色素安全性良好，但其昆虫来源使其不适合素食者和部分宗教饮食，欧盟要求标注来源信息。',
    warning: '素食者和部分宗教饮食者需注意其昆虫来源',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e161b',
    name: '叶黄素',
    aliases: ['E161b', 'Lutein'],
    code: 'E161b',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、糖果、乳制品、营养强化食品',
    summary: '天然类胡萝卜素，兼具护眼功能',
    detail: '叶黄素天然存在于万寿菊等植物中，是人眼黄斑区的重要色素，具有过滤蓝光和抗氧化功能。作为食品色素呈黄至橙黄色，同时可作为营养强化剂，JECFA未设定ADI值，安全性极高。',
    warning: '',
    source: 'GB2760-2024 / JECFA第63次评估报告'
  },
  {
    id: 'radish-red',
    name: '萝卜红',
    aliases: ['Radish Red', '红萝卜色素'],
    code: '—',
    category: '色素',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '饮料、糖果、果冻、糕点',
    summary: '天然红色素，色泽鲜艳稳定性好',
    detail: '萝卜红从红心萝卜中提取，主要成分为花青素类化合物，呈鲜艳的紫红色。在酸性条件下色泽稳定，耐光耐热性较好，是中国特有的天然食用色素品种，安全性良好。',
    warning: '',
    source: 'GB2760-2024 / 中国食品添加剂标准'
  },
  {
    id: 'e464',
    name: '羟丙基甲基纤维素',
    aliases: ['E464', 'HPMC', 'Hypromellose'],
    code: 'E464',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '冰淇淋、烘焙食品、素肉、片剂',
    summary: '改性纤维素，素食胶囊和素肉的关键原料',
    detail: '羟丙基甲基纤维素由纤维素经醚化改性制得，具有热凝胶特性——加热时形成凝胶，冷却后恢复液态。这一独特性质使其成为素食胶囊壳和无麸质烘焙的核心原料，不被人体消化吸收，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e1400',
    name: '变性淀粉',
    aliases: ['E1400', 'Modified Starch', '改性淀粉'],
    code: 'E1400',
    category: '增稠剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '酱料、速冻食品、酸奶、肉制品',
    summary: '物理或化学改性的淀粉，用途极广',
    detail: '变性淀粉通过物理、酶法或化学处理改善天然淀粉的耐热、耐酸、耐剪切和冻融稳定性，是食品工业中使用量最大的改性胶体之一。在体内与普通淀粉一样被消化酶水解为葡萄糖吸收，JECFA对大多数变性淀粉未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e475',
    name: '聚甘油脂肪酸酯',
    aliases: ['E475', 'Polyglycerol Esters of Fatty Acids', 'PGE'],
    code: 'E475',
    category: '乳化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-25mg/kg体重',
    commonFoods: '冰淇淋、蛋糕、巧克力、人造奶油',
    summary: '高效乳化剂，冰淇淋抗融化效果显著',
    detail: '聚甘油脂肪酸酯由聚甘油与脂肪酸酯化制得，HLB值范围宽，兼具乳化和结晶调节功能。在冰淇淋中可显著改善抗融化性和口感细腻度，在巧克力中改善流动性，在体内水解为甘油和脂肪酸正常代谢。',
    warning: '',
    source: 'GB2760-2024 / JECFA第20次评估报告'
  },
  {
    id: 'rosemary-extract',
    name: '迷迭香提取物',
    aliases: ['Rosemary Extract', '迷迭香酸', 'E915'],
    code: '—',
    category: '抗氧化剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '食用油、肉制品、坚果、酱料',
    summary: '天然植物抗氧化剂，效果优于合成抗氧化剂',
    detail: '迷迭香提取物主要含鼠尾草酸和迷迭香酸，通过捕获自由基和螯合金属离子双重机制抗氧化，对油脂的抗氧化效果甚至优于BHA和BHT。作为天然植物提取物，消费者接受度高，是替代合成抗氧化剂的首选。',
    warning: '',
    source: 'GB2760-2024 / EFSA评估意见'
  },
  {
    id: 'e334',
    name: '酒石酸',
    aliases: ['E334', 'Tartaric Acid'],
    code: 'E334',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-30mg/kg体重',
    commonFoods: '饮料、葡萄酒、糖果、烘焙食品',
    summary: '葡萄中天然存在的有机酸，酸味尖锐',
    detail: '酒石酸天然存在于葡萄和罗望子中，是葡萄酒中主要的有机酸。其酸味比柠檬酸更尖锐和收敛，常用于葡萄味饮料和葡萄酒调酸。酒石酸氢钾（塔塔粉）是泡打粉的关键酸性成分，ADI值有一定限制但正常食用远不超标。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e260',
    name: '乙酸',
    aliases: ['E260', 'Acetic Acid', '冰醋酸'],
    code: 'E260',
    category: '酸度调节剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '食醋、调味品、酱菜、罐头',
    summary: '食醋的主要成分，最古老的酸味剂',
    detail: '乙酸是食醋中主要的酸味成分，由乙醇经醋酸菌发酵制得。其酸味强烈且具有特征性刺激气味，是烹饪和食品加工中最常用的酸味剂之一。在体内进入乙酰辅酶A代谢途径参与能量代谢，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'e170',
    name: '碳酸钙',
    aliases: ['E170', 'Calcium Carbonate'],
    code: 'E170',
    category: '膨松剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '面包、饼干、钙强化食品、面团改良剂',
    summary: '天然矿物质，兼具膨松和钙强化功能',
    detail: '碳酸钙在高温下分解释放二氧化碳起膨松作用，同时可中和面团酸性。作为钙强化剂可显著提高食品钙含量，在体内转化为钙离子和碳酸参与正常代谢，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'e536',
    name: '亚铁氰化钾',
    aliases: ['E536', 'Potassium Ferrocyanide', '黄血盐钾'],
    code: 'E536',
    category: '其他',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-0.025mg/kg体重',
    commonFoods: '食盐',
    summary: '食盐抗结剂，名称含"氰"但实际安全',
    detail: '亚铁氰化钾在食盐中添加量极低（≤10mg/kg），用于防止食盐结块。虽然名称含"氰"，但亚铁氰根与铁离子结合极为牢固，在烹饪温度下不会释放氰化物，实际安全性良好。争议主要来自名称引起的公众恐慌，JECFA设定了极低的ADI值。',
    warning: '名称含"氰"但烹饪条件下不释放氰化物，无需恐慌',
    source: 'GB2760-2024 / JECFA第26次评估报告'
  },
  {
    id: 'e509',
    name: '氯化钙',
    aliases: ['E509', 'Calcium Chloride'],
    code: 'E509',
    category: '稳定剂',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '豆腐、奶酪、果蔬罐头、饮用水',
    summary: '多用途稳定剂和凝固剂',
    detail: '氯化钙在豆腐制作中作为凝固剂使豆浆形成凝胶，在奶酪中促进乳蛋白凝聚，在果蔬罐头中保持脆度。钙离子是人体必需矿物质，参与骨骼形成和神经传导，JECFA未设定ADI值。',
    warning: '',
    source: 'GB2760-2024 / JECFA第9次评估报告'
  },
  {
    id: 'e364',
    name: '琥珀酸二钠',
    aliases: ['E364', 'Disodium Succinate', '丁二酸钠'],
    code: 'E364',
    category: '其他',
    safetyLevel: '安全',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: 'ADI未规定',
    commonFoods: '调味品、方便面、酱油、肉制品',
    summary: '鲜味增强剂，贝类鲜味的主要来源',
    detail: '琥珀酸二钠天然存在于贝类中，是贝类鲜味的主要成分，鲜味特性与味精和核苷酸不同，具有独特的贝类鲜味感。与味精和核苷酸复配使用可产生层次丰富的鲜味效果，在体内参与三羧酸循环正常代谢。',
    warning: '',
    source: 'GB2760-2024 / JECFA第18次评估报告'
  },
  {
    id: 'e1520',
    name: '丙二醇',
    aliases: ['E1520', 'Propylene Glycol', 'PG'],
    code: 'E1520',
    category: '其他',
    safetyLevel: '争议',
    gbStatus: '允许',
    euStatus: '允许',
    usStatus: '允许',
    adi: '0-25mg/kg体重',
    commonFoods: '糕点、月饼、调味品、饮料',
    summary: '保湿剂和溶剂，猫科动物毒性引发关注',
    detail: '丙二醇具有优良的保湿和溶解性能，在月饼和糕点中防止水分流失保持柔软口感。争议在于猫对丙二醇极为敏感（可引起海因茨小体贫血），虽然人类代谢能力远强于猫，但大量摄入的安全性仍受关注，欧盟限制其在饮料中的使用量。',
    warning: '避免长期大量摄入含丙二醇的食品',
    source: 'GB2760-2024 / JECFA第17次评估报告'
  }
]

module.exports = { additiveData }
